### ISSUE TITLE
Request for Merging Backend Repository into Frontend Repository while Preserving Git Histories

### ISSUE THREAD

**Issue by IkboljonMe** [Yooupy/rest-api-backend#6]
We would like to request the merging of our backend repository into our [frontend repository ](https://github.com/Yooupy/rest-api-frontend)while preserving all git histories. The reason for this request is to streamline our development process and ensure that all code related to our project is contained within a single repository. Check frontend repo [here](https://github.com/Yooupy/rest-api-frontend)

**Comment by IkboljonMe** [comment]
@botirjonshokirov  Please, take a look and close all coming PR's till 15:30!

**Comment by IkboljonMe** [comment]
@botirjonshokirov   is it ready?

**Comment by IkboljonMe** [comment]
Done, we moved this repo part of other repo. This repo should be archived.

**Comment by botirjonshokirov** [comment]
Okay 👍
